//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.plugin.Orders.ExtendedShipment.webBarCode {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webBarCode.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GatewayPostnode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GatewayPostnode(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GatewayPostnode", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GatewayPostnodeAsync(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMassBarcode24", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Response getMassBarcode24(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMassBarcode24", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Response> getMassBarcode24Async(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMassBarcode24_v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Response getMassBarcode24_v2(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMassBarcode24_v2", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Response> getMassBarcode24_v2Async(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMassBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeResponse getMassBarcode(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMassBarcode", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeResponse> getMassBarcodeAsync(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getcity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityResponse getcity(Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getcity", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityResponse> getcityAsync(Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setpassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setpassword(string postnode, string password, string admincode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setpassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setpasswordAsync(string postnode, string password, string admincode);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMassBarcode24", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMassBarcode24Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string PostNodeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int TypeCode;
        
        public getMassBarcode24Request() {
        }
        
        public getMassBarcode24Request(string UserName, string Password, string PostNodeCode, string CityCode, int TypeCode) {
            this.UserName = UserName;
            this.Password = Password;
            this.PostNodeCode = PostNodeCode;
            this.CityCode = CityCode;
            this.TypeCode = TypeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMassBarcode24Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMassBarcode24Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string getMassBarcode24Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Barcode;
        
        public getMassBarcode24Response() {
        }
        
        public getMassBarcode24Response(string getMassBarcode24Result, string Barcode) {
            this.getMassBarcode24Result = getMassBarcode24Result;
            this.Barcode = Barcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMassBarcode24_v2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMassBarcode24_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string PostNodeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataSet BarcodeData;
        
        public getMassBarcode24_v2Request() {
        }
        
        public getMassBarcode24_v2Request(string UserName, string Password, string PostNodeCode, System.Data.DataSet BarcodeData) {
            this.UserName = UserName;
            this.Password = Password;
            this.PostNodeCode = PostNodeCode;
            this.BarcodeData = BarcodeData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMassBarcode24_v2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMassBarcode24_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet getMassBarcode24_v2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string messagetext;
        
        public getMassBarcode24_v2Response() {
        }
        
        public getMassBarcode24_v2Response(System.Data.DataSet getMassBarcode24_v2Result, string messagetext) {
            this.getMassBarcode24_v2Result = getMassBarcode24_v2Result;
            this.messagetext = messagetext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMassBarcode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMassBarcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string PostNodeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int TypeCode;
        
        public getMassBarcodeRequest() {
        }
        
        public getMassBarcodeRequest(string UserName, string Password, string PostNodeCode, string CityCode, int TypeCode) {
            this.UserName = UserName;
            this.Password = Password;
            this.PostNodeCode = PostNodeCode;
            this.CityCode = CityCode;
            this.TypeCode = TypeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMassBarcodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getMassBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string getMassBarcodeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Barcode;
        
        public getMassBarcodeResponse() {
        }
        
        public getMassBarcodeResponse(string getMassBarcodeResult, string Barcode) {
            this.getMassBarcodeResult = getMassBarcodeResult;
            this.Barcode = Barcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getcity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getcityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int type;
        
        public getcityRequest() {
        }
        
        public getcityRequest(string username, string password, int type) {
            this.username = username;
            this.password = password;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getcityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getcityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet getcityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public getcityResponse() {
        }
        
        public getcityResponse(System.Data.DataSet getcityResult, string error) {
            this.getcityResult = getcityResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap>, Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GatewayPostnode(string UserName, string Password) {
            return base.Channel.GatewayPostnode(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GatewayPostnodeAsync(string UserName, string Password) {
            return base.Channel.GatewayPostnodeAsync(UserName, Password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Response Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap.getMassBarcode24(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Request request) {
            return base.Channel.getMassBarcode24(request);
        }
        
        public string getMassBarcode24(string UserName, string Password, string PostNodeCode, string CityCode, int TypeCode, out string Barcode) {
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Request inValue = new Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Request();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.PostNodeCode = PostNodeCode;
            inValue.CityCode = CityCode;
            inValue.TypeCode = TypeCode;
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Response retVal = ((Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap)(this)).getMassBarcode24(inValue);
            Barcode = retVal.Barcode;
            return retVal.getMassBarcode24Result;
        }
        
        public System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Response> getMassBarcode24Async(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24Request request) {
            return base.Channel.getMassBarcode24Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Response Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap.getMassBarcode24_v2(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Request request) {
            return base.Channel.getMassBarcode24_v2(request);
        }
        
        public System.Data.DataSet getMassBarcode24_v2(string UserName, string Password, string PostNodeCode, System.Data.DataSet BarcodeData, out string messagetext) {
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Request inValue = new Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Request();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.PostNodeCode = PostNodeCode;
            inValue.BarcodeData = BarcodeData;
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Response retVal = ((Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap)(this)).getMassBarcode24_v2(inValue);
            messagetext = retVal.messagetext;
            return retVal.getMassBarcode24_v2Result;
        }
        
        public System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Response> getMassBarcode24_v2Async(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcode24_v2Request request) {
            return base.Channel.getMassBarcode24_v2Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeResponse Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap.getMassBarcode(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeRequest request) {
            return base.Channel.getMassBarcode(request);
        }
        
        public string getMassBarcode(string UserName, string Password, string PostNodeCode, string CityCode, int TypeCode, out string Barcode) {
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeRequest inValue = new Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.PostNodeCode = PostNodeCode;
            inValue.CityCode = CityCode;
            inValue.TypeCode = TypeCode;
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeResponse retVal = ((Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap)(this)).getMassBarcode(inValue);
            Barcode = retVal.Barcode;
            return retVal.getMassBarcodeResult;
        }
        
        public System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeResponse> getMassBarcodeAsync(Nop.plugin.Orders.ExtendedShipment.webBarCode.getMassBarcodeRequest request) {
            return base.Channel.getMassBarcodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityResponse Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap.getcity(Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityRequest request) {
            return base.Channel.getcity(request);
        }
        
        public System.Data.DataSet getcity(string username, string password, int type, out string error) {
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityRequest inValue = new Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.type = type;
            Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityResponse retVal = ((Nop.plugin.Orders.ExtendedShipment.webBarCode.Service1Soap)(this)).getcity(inValue);
            error = retVal.error;
            return retVal.getcityResult;
        }
        
        public System.Threading.Tasks.Task<Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityResponse> getcityAsync(Nop.plugin.Orders.ExtendedShipment.webBarCode.getcityRequest request) {
            return base.Channel.getcityAsync(request);
        }
        
        public string setpassword(string postnode, string password, string admincode) {
            return base.Channel.setpassword(postnode, password, admincode);
        }
        
        public System.Threading.Tasks.Task<string> setpasswordAsync(string postnode, string password, string admincode) {
            return base.Channel.setpasswordAsync(postnode, password, admincode);
        }
    }
}
